import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

public class FixPad
{
    private JPanel panel1;
    private JTabbedPane tabbedPane1;
    private JEditorPane editorPane1;
    private JEditorPane editorPane2;
    private JEditorPane editorPane3;
    private FileManager fman = new FileManager();

    private void startFman ()
    {
        fman.put(editorPane1);
        fman.put(editorPane2);
        fman.put(editorPane3);
        fman.start();
    }

    public static void main (String[] args)
    {
        JFrame frame = new JFrame("FixPad");
        FixPad pad = new FixPad();
        frame.addWindowListener(new WindowListener()
        {
            @Override
            public void windowOpened (WindowEvent e)
            {

            }

            @Override
            public void windowClosing (WindowEvent e)
            {
                pad.fman.stop();
            }

            @Override
            public void windowClosed (WindowEvent e)
            {

            }

            @Override
            public void windowIconified (WindowEvent e)
            {

            }

            @Override
            public void windowDeiconified (WindowEvent e)
            {

            }

            @Override
            public void windowActivated (WindowEvent e)
            {

            }

            @Override
            public void windowDeactivated (WindowEvent e)
            {

            }
        });
        frame.setContentPane(pad.panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);
        pad.startFman();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane1 = new JTabbedPane();
        panel1.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new CardLayout(0, 0));
        tabbedPane1.addTab("Untitled", panel2);
        editorPane1 = new JEditorPane();
        editorPane1.setBackground(new Color(-15987184));
        editorPane1.setCaretColor(new Color(-1170650));
        Font editorPane1Font = this.$$$getFont$$$("Consolas", -1, 20, editorPane1.getFont());
        if (editorPane1Font != null)
        {
            editorPane1.setFont(editorPane1Font);
        }
        editorPane1.setForeground(new Color(-4539718));
        panel2.add(editorPane1, "Card1");
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new CardLayout(0, 0));
        tabbedPane1.addTab("Untitled", panel3);
        editorPane2 = new JEditorPane();
        panel3.add(editorPane2, "Card1");
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new CardLayout(0, 0));
        tabbedPane1.addTab("Untitled", panel4);
        editorPane3 = new JEditorPane();
        panel4.add(editorPane3, "Card1");
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$ (String fontName, int style, int size, Font currentFont)
    {
        if (currentFont == null)
        {
            return null;
        }
        String resultName;
        if (fontName == null)
        {
            resultName = currentFont.getName();
        }
        else
        {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1'))
            {
                resultName = fontName;
            }
            else
            {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return panel1;
    }
}


